root: true
env:
  es6: true
  commonjs: true
parserOptions:
  ecmaVersion: 2020
globals:
  window: false
  g: true
  console: true
rules:
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-inner-declarations: error
  no-irregular-whitespace:
    - error
    - skipStrings: true
      skipComments: true
      skipRegExps: true
      skipTemplates: true
  no-undef: error
